name: Simple Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Sync Files to Server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: './'
        remote_path: '/var/www/html/cicd'
        remote_host: '34.31.159.18'
        remote_user: 'csebidhan'
        remote_key: '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAQEAxnEfA1mG1eV7YWzpqdudEMQjeOfmlCpIZxqAassmfuXVAT/PXG8t
LCgYlmZVEnRPifRHxN8N0ETbjWv1CKka1C18qYrIaTYFVXgIqJgBBQWI+dqkz2aZFwHgGr
9YNUAr2pV3gWeK9tix38VH13w9LIwg1mhTnKZaOxw3xOagSrK4aMaOYlWIubE/fylqNFJZ
OKqCHuynV4vyMDolTiCSYHYH4Ep/czGD++lSh1BKuTweJwV3jXNLXUjYmW4tjB4/NH4yce
45Q7cwoZSPFS3ZYHetr74oPq+/HHZj8y9MypZeZnoYtez21WLV41MF4ukKt5kMXe0QsLUA
iFt+SfM69wAAA8iA0a4JgNGuCQAAAAdzc2gtcnNhAAABAQDGcR8DWYbV5XthbOmp250QxC
N45+aUKkhnGoBqyyZ+5dUBP89cby0sKBiWZlUSdE+J9EfE3w3QRNuNa/UIqRrULXypishp
NgVVeAiomAEFBYj52qTPZpkXAeAav1g1QCvalXeBZ4r22LHfxUfXfD0sjCDWaFOcplo7HD
fE5qBKsrhoxo5iVYi5sT9/KWo0Ulk4qoIe7KdXi/IwOiVOIJJgdgfgSn9zMYP76VKHUEq5
PB4nBXeNc0tdSNiZbi2MHj80fjJx7jlDtzChlI8VLdlgd62vvig+r78cdmPzL0zKll5meh
i17PbVYtXjUwXi6Qq3mQxd7RCwtQCIW35J8zr3AAAAAwEAAQAAAQAqTaUx3pz67j/eJgyt
9C5Ii7eQJ8ek4Fqs+B5WJdagCLje2k6HQwAbQLT1Iv2RwI/QNe4yzuYv9u3i+Re0b/BTOR
sxPW+51hVPAha+ciENg/+OXAj0Wcfa+sBek1nniDWRFHn0cTFTrCBHNtQ44LhdzcWWT4k7
hM8JeNt+szeKlKzU3fIxpGZWuJqEPUZIKFZ8qO7YGr5z3I/+7IGix0OPWxq2fX/iHC5V4d
a1TtUBQPZ/sgH3EmFnTa3vlewCOD1CBYNbQbt5UY0+B9pXa0/2DZVA9aj9f5j2uj4Ar1Nu
wFlxxFPQOL+yMOY63ZdcrTh6rySxWzGjQ3y32JWqCeiBAAAAgEPzfvaKNA2D2qa+MF8Lei
gvXjzTZLSdnSXx39X74TLX5E+0UT7L4TwQ0og3YKZWOiAJwDCc+O3SHf4FjXFUXyEBWmM4
BcBzxxN9hdNF6yqU2daRp+kvq7QgMKletYgQP0YKXUXTrXS0ZqudhOsmncbZNOAG6sYAAe
MF/fODK2wgAAAAgQDlJyd9gr/94CBx1jH2y7p/NmYPCF8Tkh7GbEsdgUSAM6caM7DFp8jd
xdZczBwO0ghSH8atIFE7kLm2oFEICluP5myWFnEg8u+Wt3QH4FIyyK/j3hbfx3caF26Vvs
KxL9BqcuMBAUuIJKAFI58lezcT/Kl0zKbo6cbEi5en7WZBNwAAAIEA3bDeUW9qAXTu32sl
eGcrv5q/0EgW5yawLuh68JQ0ZzjfFrClaM+j774yigDzzV+I0scVtxyYHMcroXuQCxmRSz
Kt2YtZNC9WqYQB67mjPlfEECKgmImIv0oy1ZvfqPYMJbdrYUiMGupu2UFdPPP4c7xtUnpj
zZ3BSWTpQ2TutEEAAAATY3NlYmlkaGFuQGdtYWlsLmNvbQ==
-----END OPENSSH PRIVATE KEY-----'

  