name: Simple Deplay

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Sync Files to Server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: './'
        remote_path: '/var/www/html/cicd'
        remote_host: '34.31.159.18'
        remote_user: 'ubuntu'
        remote_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcpT4Ig+kCpKRQftZQbxtlYJwah5VDV8lE3f9xjVldTJX4bxeJvGxSogB5SK37lKaO8588DIZULAjvaUv0Mh9ewTR9yU5NKyUNGOQTu6Kt1MhRo7YWNbrWQ7/32WXtCeHv1o23Amm+BPX1Bc+mDKKdSs4KdFBcNBAGNn0/DQBVjkRTxUriDbOZsojOY/fzHsHCqYIpQOblICW62jB2OLNp0eXRChnZ226n3KUjlt0ZkP3HxbohyiSuOF29OLdBOtmGO9GVVTyrxYxN4BNVJSivrcvAppj3J3ILHmgKGcaoV9gCUXZkpikI222cxGlg+OnK6vad5jgJVAWxgw2k66NP csebidhan@gmail.com'

  