name: Simple Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Sync Files to Server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: './'
        remote_path: '/var/www/html/cicd'
        remote_host: '34.31.159.18'
        remote_user: 'csebidhan'
        remote_key: '-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDbeO9mQ7jKcWAPgPMsB2XqAAAAGAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQDgtnf2IODHGf5Zzpgfq4P3vII+BTSsowK88YzuXjKYQE9HpyLbSmG7G1fEnlOWMVXeZqANg/WEyCNIAE+T/Qnc88bhP/3oGIzPkLBkaioKeJVtw6kFIzrkyk5fmmobpBmL5tFdGFGizI1p92beFPJxC2X6H43wS2YvUMxBC93VRUL9mWHNLus7/3Hz5P78zI159r+ykSzuKfBoIpGQtemqG1J+5B/XSnbg0kGsoYGT9yCaUfXTOF7fchv8Jybvjk3KnppJz2BQ8QhaismUb0wdt2fWC0S2Ed9mNwUCH8gYc9Gy9R7teKvjY652W6rrMPvxeQq/Ts3NTQkN/6OWpIB3AAAD0IP5VZKqmzEb7Vj4HoC7gNMp+bqTVqvTIqfnC6f8cXKuoT9ZwOYlnVeDL0q2S1eZurXiAtwrFMSSGpZtuSuysaDXb+Mmrtj2wNCnmnEgpx6/CnMHqQ4CGwEYtwlpH/MC1lpQK1QSFBHuolY9rvMAAEjv0Ux31VwPg1hijtwgOo0xodbjmay+PtHLMo4fEQvEQXAp0sxNeCY2gxC+jlAUFHIY8gBxW8kuc65IL/MzBgz9oW3HfAoQV6etapvZLK/dMqHQ8KydsRoV1VFzYxRDEajicCoqtryoGNNHwy96knLu6rwLZ6rNhXZa0lQFBpUXsXdQt96WTr0eo9eg7ELCiCMImWirEVVg1QZlQ/1/pA4qRldJ0lyTkaU0SG2Y3esRWC7Y8jSuXMnFUi5taJTRlztfetcAlrIXn1oROK8P6ruiVXVl2W2Ry+3RmUXpqRDYBQ41/DmEqU+qo4NMWEvwZRFbe1ukntNAAmI7Bgmo/BvsC/GnGHxhoNsP9cdz0unOR8nHPxiDL1Bijn4jmtcQk5/iNZTBi136aEdh03Pmai0femjKrcnsJo0HMQOuCrPavbh2H5GkkYLWVII1xSyUBYx86xQes9RBPRFTAwJ3ErZsYMuAWsheK6HPtd/mdpAfdlrDthzQFXLzaMu8hqNTCEYWQkJaePAt9SFbFJnvBAPomAf2w81lW0Smpga9XK940tEOht6ZXqKbPxabRduTZ3j++taBG+Q6JAaGsy3JAHbnw15vLGaZo90wh5TDqw9j02vZaSQgEnl3HlrVnlTR7oCKT24iXsEMTVCEkt3Ttc5pL93ke+3uFrizJApbgctkMLDj/R+rwXZx1IGpaNfe8s2wD9tQR58hEW+YtJV8rJYcDBGCl2hZW38gRu00FOe10y+9yBPMT5QWs2vPrxIo51CAUrTY858DC24OsaR1XVE7saTMhWrah0bYGCNRtTzSTGZXGisnaw9icnbRyzrPCgaITkIfZmGQAJSlGx/2vXUk94sJ25gceWSbJhcG0V0+YVEDuvb+vRmD7ye2Cwwcjruv0t8oaUNqHitEJgMoxhwxLGVNP5tgzvcDaz1Lrx8LM9c7B/CCrOPKAYbJZ9pWiPOZkwXhkwXZL5RSizUB0kmk3BUOFyg6l4W17zJ7cy07kZVtPBgMMLjPrsCudA1+IBHRzNa+WmkXfX6xZmPbBbvB7ggDp3t+Z8JD6SM/cXVCTYcYKDdLRxp9ISgaif58cl37fKVavtouIM8FMCLSPtPELZ/8ym9al1Gl50ASiUjO+/wKYW13/6pXtULPsbf162o=-----END OPENSSH PRIVATE KEY-----'

  