name: Simple Deplay

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Sync Files to Server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: './'
        remote_path: '/var/www/html/cicd'
        remote_host: ${{ secrets.SERVER_IP }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}

   # - name: Run php artisan optimize
      run: |
        ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/cicd"
