    - name: Sync Files to Server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: './'
        remote_path: '/var/www/html/cicd'
        remote_host: '34.31.159.18'
        remote_user: 'csebidhan'
        remote_key: |
          ${{ secrets.SSH_PRIVATE_KEY }}